/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.support.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.yithro.support.model.SupportLevelAgreement;
import com.liferay.yithro.support.service.SupportLevelAgreementLocalService;
import com.liferay.yithro.support.service.persistence.SupportLaborPersistence;
import com.liferay.yithro.support.service.persistence.SupportLevelAgreementPersistence;
import com.liferay.yithro.support.service.persistence.SupportTeamPersistence;
import com.liferay.yithro.support.service.persistence.SupportWorkerPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the support level agreement local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.yithro.support.service.impl.SupportLevelAgreementLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.yithro.support.service.impl.SupportLevelAgreementLocalServiceImpl
 * @generated
 */
public abstract class SupportLevelAgreementLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   SupportLevelAgreementLocalService {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SupportLevelAgreementLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.yithro.support.service.SupportLevelAgreementLocalServiceUtil</code>.
	 */

	/**
	 * Adds the support level agreement to the database. Also notifies the appropriate model listeners.
	 *
	 * @param supportLevelAgreement the support level agreement
	 * @return the support level agreement that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SupportLevelAgreement addSupportLevelAgreement(
		SupportLevelAgreement supportLevelAgreement) {

		supportLevelAgreement.setNew(true);

		return supportLevelAgreementPersistence.update(supportLevelAgreement);
	}

	/**
	 * Creates a new support level agreement with the primary key. Does not add the support level agreement to the database.
	 *
	 * @param supportLevelAgreementId the primary key for the new support level agreement
	 * @return the new support level agreement
	 */
	@Override
	@Transactional(enabled = false)
	public SupportLevelAgreement createSupportLevelAgreement(
		long supportLevelAgreementId) {

		return supportLevelAgreementPersistence.create(supportLevelAgreementId);
	}

	/**
	 * Deletes the support level agreement with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param supportLevelAgreementId the primary key of the support level agreement
	 * @return the support level agreement that was removed
	 * @throws PortalException if a support level agreement with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SupportLevelAgreement deleteSupportLevelAgreement(
			long supportLevelAgreementId)
		throws PortalException {

		return supportLevelAgreementPersistence.remove(supportLevelAgreementId);
	}

	/**
	 * Deletes the support level agreement from the database. Also notifies the appropriate model listeners.
	 *
	 * @param supportLevelAgreement the support level agreement
	 * @return the support level agreement that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SupportLevelAgreement deleteSupportLevelAgreement(
		SupportLevelAgreement supportLevelAgreement) {

		return supportLevelAgreementPersistence.remove(supportLevelAgreement);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			SupportLevelAgreement.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return supportLevelAgreementPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.yithro.support.model.impl.SupportLevelAgreementModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return supportLevelAgreementPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.yithro.support.model.impl.SupportLevelAgreementModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return supportLevelAgreementPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return supportLevelAgreementPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return supportLevelAgreementPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public SupportLevelAgreement fetchSupportLevelAgreement(
		long supportLevelAgreementId) {

		return supportLevelAgreementPersistence.fetchByPrimaryKey(
			supportLevelAgreementId);
	}

	/**
	 * Returns the support level agreement with the primary key.
	 *
	 * @param supportLevelAgreementId the primary key of the support level agreement
	 * @return the support level agreement
	 * @throws PortalException if a support level agreement with the primary key could not be found
	 */
	@Override
	public SupportLevelAgreement getSupportLevelAgreement(
			long supportLevelAgreementId)
		throws PortalException {

		return supportLevelAgreementPersistence.findByPrimaryKey(
			supportLevelAgreementId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			supportLevelAgreementLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SupportLevelAgreement.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"supportLevelAgreementId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			supportLevelAgreementLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			SupportLevelAgreement.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"supportLevelAgreementId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			supportLevelAgreementLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SupportLevelAgreement.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"supportLevelAgreementId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return supportLevelAgreementLocalService.deleteSupportLevelAgreement(
			(SupportLevelAgreement)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return supportLevelAgreementPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the support level agreements.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.yithro.support.model.impl.SupportLevelAgreementModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of support level agreements
	 * @param end the upper bound of the range of support level agreements (not inclusive)
	 * @return the range of support level agreements
	 */
	@Override
	public List<SupportLevelAgreement> getSupportLevelAgreements(
		int start, int end) {

		return supportLevelAgreementPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of support level agreements.
	 *
	 * @return the number of support level agreements
	 */
	@Override
	public int getSupportLevelAgreementsCount() {
		return supportLevelAgreementPersistence.countAll();
	}

	/**
	 * Updates the support level agreement in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param supportLevelAgreement the support level agreement
	 * @return the support level agreement that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SupportLevelAgreement updateSupportLevelAgreement(
		SupportLevelAgreement supportLevelAgreement) {

		return supportLevelAgreementPersistence.update(supportLevelAgreement);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SupportLevelAgreementLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		supportLevelAgreementLocalService =
			(SupportLevelAgreementLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SupportLevelAgreementLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SupportLevelAgreement.class;
	}

	protected String getModelClassName() {
		return SupportLevelAgreement.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				supportLevelAgreementPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@Reference
	protected SupportLaborPersistence supportLaborPersistence;

	protected SupportLevelAgreementLocalService
		supportLevelAgreementLocalService;

	@Reference
	protected SupportLevelAgreementPersistence supportLevelAgreementPersistence;

	@Reference
	protected SupportTeamPersistence supportTeamPersistence;

	@Reference
	protected SupportWorkerPersistence supportWorkerPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}