/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.support.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.yithro.support.model.SupportLevelAgreement;
import com.liferay.yithro.support.model.SupportLevelAgreementModel;
import com.liferay.yithro.support.model.SupportLevelAgreementSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SupportLevelAgreement service. Represents a row in the &quot;Yithro_SupportLevelAgreement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>SupportLevelAgreementModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SupportLevelAgreementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportLevelAgreementImpl
 * @generated
 */
@JSON(strict = true)
public class SupportLevelAgreementModelImpl
	extends BaseModelImpl<SupportLevelAgreement>
	implements SupportLevelAgreementModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a support level agreement model instance should use the <code>SupportLevelAgreement</code> interface instead.
	 */
	public static final String TABLE_NAME = "Yithro_SupportLevelAgreement";

	public static final Object[][] TABLE_COLUMNS = {
		{"supportLevelAgreementId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"description", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("supportLevelAgreementId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Yithro_SupportLevelAgreement (supportLevelAgreementId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,description VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Yithro_SupportLevelAgreement";

	public static final String ORDER_BY_JPQL =
		" ORDER BY supportLevelAgreement.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Yithro_SupportLevelAgreement.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long NAME_COLUMN_BITMASK = 1L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SupportLevelAgreement toModel(
		SupportLevelAgreementSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		SupportLevelAgreement model = new SupportLevelAgreementImpl();

		model.setSupportLevelAgreementId(
			soapModel.getSupportLevelAgreementId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SupportLevelAgreement> toModels(
		SupportLevelAgreementSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SupportLevelAgreement> models =
			new ArrayList<SupportLevelAgreement>(soapModels.length);

		for (SupportLevelAgreementSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public SupportLevelAgreementModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _supportLevelAgreementId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSupportLevelAgreementId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _supportLevelAgreementId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SupportLevelAgreement.class;
	}

	@Override
	public String getModelClassName() {
		return SupportLevelAgreement.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SupportLevelAgreement, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SupportLevelAgreement, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SupportLevelAgreement, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SupportLevelAgreement)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SupportLevelAgreement, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SupportLevelAgreement, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SupportLevelAgreement)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SupportLevelAgreement, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SupportLevelAgreement, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, SupportLevelAgreement>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			SupportLevelAgreement.class.getClassLoader(),
			SupportLevelAgreement.class, ModelWrapper.class);

		try {
			Constructor<SupportLevelAgreement> constructor =
				(Constructor<SupportLevelAgreement>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<SupportLevelAgreement, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SupportLevelAgreement, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SupportLevelAgreement, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SupportLevelAgreement, Object>>();
		Map<String, BiConsumer<SupportLevelAgreement, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<SupportLevelAgreement, ?>>();

		attributeGetterFunctions.put(
			"supportLevelAgreementId",
			SupportLevelAgreement::getSupportLevelAgreementId);
		attributeSetterBiConsumers.put(
			"supportLevelAgreementId",
			(BiConsumer<SupportLevelAgreement, Long>)
				SupportLevelAgreement::setSupportLevelAgreementId);
		attributeGetterFunctions.put(
			"companyId", SupportLevelAgreement::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SupportLevelAgreement, Long>)
				SupportLevelAgreement::setCompanyId);
		attributeGetterFunctions.put(
			"userId", SupportLevelAgreement::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<SupportLevelAgreement, Long>)
				SupportLevelAgreement::setUserId);
		attributeGetterFunctions.put(
			"createDate", SupportLevelAgreement::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SupportLevelAgreement, Date>)
				SupportLevelAgreement::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SupportLevelAgreement::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SupportLevelAgreement, Date>)
				SupportLevelAgreement::setModifiedDate);
		attributeGetterFunctions.put("name", SupportLevelAgreement::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<SupportLevelAgreement, String>)
				SupportLevelAgreement::setName);
		attributeGetterFunctions.put(
			"description", SupportLevelAgreement::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<SupportLevelAgreement, String>)
				SupportLevelAgreement::setDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getSupportLevelAgreementId() {
		return _supportLevelAgreementId;
	}

	@Override
	public void setSupportLevelAgreementId(long supportLevelAgreementId) {
		_supportLevelAgreementId = supportLevelAgreementId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SupportLevelAgreement.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SupportLevelAgreement toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SupportLevelAgreement>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SupportLevelAgreementImpl supportLevelAgreementImpl =
			new SupportLevelAgreementImpl();

		supportLevelAgreementImpl.setSupportLevelAgreementId(
			getSupportLevelAgreementId());
		supportLevelAgreementImpl.setCompanyId(getCompanyId());
		supportLevelAgreementImpl.setUserId(getUserId());
		supportLevelAgreementImpl.setCreateDate(getCreateDate());
		supportLevelAgreementImpl.setModifiedDate(getModifiedDate());
		supportLevelAgreementImpl.setName(getName());
		supportLevelAgreementImpl.setDescription(getDescription());

		supportLevelAgreementImpl.resetOriginalValues();

		return supportLevelAgreementImpl;
	}

	@Override
	public int compareTo(SupportLevelAgreement supportLevelAgreement) {
		int value = 0;

		value = getName().compareTo(supportLevelAgreement.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SupportLevelAgreement)) {
			return false;
		}

		SupportLevelAgreement supportLevelAgreement =
			(SupportLevelAgreement)obj;

		long primaryKey = supportLevelAgreement.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		SupportLevelAgreementModelImpl supportLevelAgreementModelImpl = this;

		supportLevelAgreementModelImpl._setModifiedDate = false;

		supportLevelAgreementModelImpl._originalName =
			supportLevelAgreementModelImpl._name;

		supportLevelAgreementModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SupportLevelAgreement> toCacheModel() {
		SupportLevelAgreementCacheModel supportLevelAgreementCacheModel =
			new SupportLevelAgreementCacheModel();

		supportLevelAgreementCacheModel.supportLevelAgreementId =
			getSupportLevelAgreementId();

		supportLevelAgreementCacheModel.companyId = getCompanyId();

		supportLevelAgreementCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			supportLevelAgreementCacheModel.createDate = createDate.getTime();
		}
		else {
			supportLevelAgreementCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			supportLevelAgreementCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			supportLevelAgreementCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		supportLevelAgreementCacheModel.name = getName();

		String name = supportLevelAgreementCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			supportLevelAgreementCacheModel.name = null;
		}

		supportLevelAgreementCacheModel.description = getDescription();

		String description = supportLevelAgreementCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			supportLevelAgreementCacheModel.description = null;
		}

		return supportLevelAgreementCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SupportLevelAgreement, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SupportLevelAgreement, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SupportLevelAgreement, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((SupportLevelAgreement)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SupportLevelAgreement, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SupportLevelAgreement, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SupportLevelAgreement, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((SupportLevelAgreement)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SupportLevelAgreement>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _supportLevelAgreementId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _originalName;
	private String _description;
	private long _columnBitmask;
	private SupportLevelAgreement _escapedModel;

}