/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.rules.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.yithro.rules.model.Rule;
import com.liferay.yithro.rules.model.RuleModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Rule service. Represents a row in the &quot;Yithro_Rule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>RuleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RuleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RuleImpl
 * @generated
 */
public class RuleModelImpl extends BaseModelImpl<Rule> implements RuleModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rule model instance should use the <code>Rule</code> interface instead.
	 */
	public static final String TABLE_NAME = "Yithro_Rule";

	public static final Object[][] TABLE_COLUMNS = {
		{"ruleId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"objectName", Types.VARCHAR}, {"objectEvent", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ruleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("objectName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("objectEvent", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Yithro_Rule (ruleId LONG not null primary key,name VARCHAR(75) null,objectName VARCHAR(75) null,objectEvent VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Yithro_Rule";

	public static final String ORDER_BY_JPQL = " ORDER BY rule.ruleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Yithro_Rule.ruleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long OBJECTEVENT_COLUMN_BITMASK = 1L;

	public static final long OBJECTNAME_COLUMN_BITMASK = 2L;

	public static final long RULEID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public RuleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ruleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRuleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ruleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Rule.class;
	}

	@Override
	public String getModelClassName() {
		return Rule.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Rule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Rule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Rule, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Rule)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Rule, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Rule, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Rule)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Rule, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Rule, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Rule>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Rule.class.getClassLoader(), Rule.class, ModelWrapper.class);

		try {
			Constructor<Rule> constructor =
				(Constructor<Rule>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Rule, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Rule, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Rule, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Rule, Object>>();
		Map<String, BiConsumer<Rule, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Rule, ?>>();

		attributeGetterFunctions.put("ruleId", Rule::getRuleId);
		attributeSetterBiConsumers.put(
			"ruleId", (BiConsumer<Rule, Long>)Rule::setRuleId);
		attributeGetterFunctions.put("name", Rule::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Rule, String>)Rule::setName);
		attributeGetterFunctions.put("objectName", Rule::getObjectName);
		attributeSetterBiConsumers.put(
			"objectName", (BiConsumer<Rule, String>)Rule::setObjectName);
		attributeGetterFunctions.put("objectEvent", Rule::getObjectEvent);
		attributeSetterBiConsumers.put(
			"objectEvent", (BiConsumer<Rule, String>)Rule::setObjectEvent);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getRuleId() {
		return _ruleId;
	}

	@Override
	public void setRuleId(long ruleId) {
		_ruleId = ruleId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getObjectName() {
		if (_objectName == null) {
			return "";
		}
		else {
			return _objectName;
		}
	}

	@Override
	public void setObjectName(String objectName) {
		_columnBitmask |= OBJECTNAME_COLUMN_BITMASK;

		if (_originalObjectName == null) {
			_originalObjectName = _objectName;
		}

		_objectName = objectName;
	}

	public String getOriginalObjectName() {
		return GetterUtil.getString(_originalObjectName);
	}

	@Override
	public String getObjectEvent() {
		if (_objectEvent == null) {
			return "";
		}
		else {
			return _objectEvent;
		}
	}

	@Override
	public void setObjectEvent(String objectEvent) {
		_columnBitmask |= OBJECTEVENT_COLUMN_BITMASK;

		if (_originalObjectEvent == null) {
			_originalObjectEvent = _objectEvent;
		}

		_objectEvent = objectEvent;
	}

	public String getOriginalObjectEvent() {
		return GetterUtil.getString(_originalObjectEvent);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Rule.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Rule toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Rule>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RuleImpl ruleImpl = new RuleImpl();

		ruleImpl.setRuleId(getRuleId());
		ruleImpl.setName(getName());
		ruleImpl.setObjectName(getObjectName());
		ruleImpl.setObjectEvent(getObjectEvent());

		ruleImpl.resetOriginalValues();

		return ruleImpl;
	}

	@Override
	public int compareTo(Rule rule) {
		long primaryKey = rule.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Rule)) {
			return false;
		}

		Rule rule = (Rule)obj;

		long primaryKey = rule.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		RuleModelImpl ruleModelImpl = this;

		ruleModelImpl._originalObjectName = ruleModelImpl._objectName;

		ruleModelImpl._originalObjectEvent = ruleModelImpl._objectEvent;

		ruleModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Rule> toCacheModel() {
		RuleCacheModel ruleCacheModel = new RuleCacheModel();

		ruleCacheModel.ruleId = getRuleId();

		ruleCacheModel.name = getName();

		String name = ruleCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			ruleCacheModel.name = null;
		}

		ruleCacheModel.objectName = getObjectName();

		String objectName = ruleCacheModel.objectName;

		if ((objectName != null) && (objectName.length() == 0)) {
			ruleCacheModel.objectName = null;
		}

		ruleCacheModel.objectEvent = getObjectEvent();

		String objectEvent = ruleCacheModel.objectEvent;

		if ((objectEvent != null) && (objectEvent.length() == 0)) {
			ruleCacheModel.objectEvent = null;
		}

		return ruleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Rule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Rule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Rule, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Rule)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Rule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Rule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Rule, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Rule)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Rule>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _ruleId;
	private String _name;
	private String _objectName;
	private String _originalObjectName;
	private String _objectEvent;
	private String _originalObjectEvent;
	private long _columnBitmask;
	private Rule _escapedModel;

}