/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.rules.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.yithro.rules.model.RuleActionData;
import com.liferay.yithro.rules.model.RuleActionDataModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RuleActionData service. Represents a row in the &quot;Yithro_RuleActionData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>RuleActionDataModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RuleActionDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RuleActionDataImpl
 * @generated
 */
public class RuleActionDataModelImpl
	extends BaseModelImpl<RuleActionData> implements RuleActionDataModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rule action data model instance should use the <code>RuleActionData</code> interface instead.
	 */
	public static final String TABLE_NAME = "Yithro_RuleActionData";

	public static final Object[][] TABLE_COLUMNS = {
		{"ruleActionDataId", Types.BIGINT}, {"ruleActionId", Types.BIGINT},
		{"field", Types.VARCHAR}, {"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ruleActionDataId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ruleActionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("field", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Yithro_RuleActionData (ruleActionDataId LONG not null primary key,ruleActionId LONG,field VARCHAR(75) null,value VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Yithro_RuleActionData";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ruleActionData.ruleActionDataId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Yithro_RuleActionData.ruleActionDataId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long RULEACTIONID_COLUMN_BITMASK = 1L;

	public static final long RULEACTIONDATAID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public RuleActionDataModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ruleActionDataId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRuleActionDataId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ruleActionDataId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RuleActionData.class;
	}

	@Override
	public String getModelClassName() {
		return RuleActionData.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RuleActionData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RuleActionData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RuleActionData, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RuleActionData)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RuleActionData, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RuleActionData, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RuleActionData)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RuleActionData, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RuleActionData, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RuleActionData>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RuleActionData.class.getClassLoader(), RuleActionData.class,
			ModelWrapper.class);

		try {
			Constructor<RuleActionData> constructor =
				(Constructor<RuleActionData>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<RuleActionData, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RuleActionData, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RuleActionData, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<RuleActionData, Object>>();
		Map<String, BiConsumer<RuleActionData, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<RuleActionData, ?>>();

		attributeGetterFunctions.put(
			"ruleActionDataId", RuleActionData::getRuleActionDataId);
		attributeSetterBiConsumers.put(
			"ruleActionDataId",
			(BiConsumer<RuleActionData, Long>)
				RuleActionData::setRuleActionDataId);
		attributeGetterFunctions.put(
			"ruleActionId", RuleActionData::getRuleActionId);
		attributeSetterBiConsumers.put(
			"ruleActionId",
			(BiConsumer<RuleActionData, Long>)RuleActionData::setRuleActionId);
		attributeGetterFunctions.put("field", RuleActionData::getField);
		attributeSetterBiConsumers.put(
			"field",
			(BiConsumer<RuleActionData, String>)RuleActionData::setField);
		attributeGetterFunctions.put("value", RuleActionData::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<RuleActionData, String>)RuleActionData::setValue);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getRuleActionDataId() {
		return _ruleActionDataId;
	}

	@Override
	public void setRuleActionDataId(long ruleActionDataId) {
		_ruleActionDataId = ruleActionDataId;
	}

	@Override
	public long getRuleActionId() {
		return _ruleActionId;
	}

	@Override
	public void setRuleActionId(long ruleActionId) {
		_columnBitmask |= RULEACTIONID_COLUMN_BITMASK;

		if (!_setOriginalRuleActionId) {
			_setOriginalRuleActionId = true;

			_originalRuleActionId = _ruleActionId;
		}

		_ruleActionId = ruleActionId;
	}

	public long getOriginalRuleActionId() {
		return _originalRuleActionId;
	}

	@Override
	public String getField() {
		if (_field == null) {
			return "";
		}
		else {
			return _field;
		}
	}

	@Override
	public void setField(String field) {
		_field = field;
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RuleActionData.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RuleActionData toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RuleActionData>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RuleActionDataImpl ruleActionDataImpl = new RuleActionDataImpl();

		ruleActionDataImpl.setRuleActionDataId(getRuleActionDataId());
		ruleActionDataImpl.setRuleActionId(getRuleActionId());
		ruleActionDataImpl.setField(getField());
		ruleActionDataImpl.setValue(getValue());

		ruleActionDataImpl.resetOriginalValues();

		return ruleActionDataImpl;
	}

	@Override
	public int compareTo(RuleActionData ruleActionData) {
		long primaryKey = ruleActionData.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RuleActionData)) {
			return false;
		}

		RuleActionData ruleActionData = (RuleActionData)obj;

		long primaryKey = ruleActionData.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		RuleActionDataModelImpl ruleActionDataModelImpl = this;

		ruleActionDataModelImpl._originalRuleActionId =
			ruleActionDataModelImpl._ruleActionId;

		ruleActionDataModelImpl._setOriginalRuleActionId = false;

		ruleActionDataModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<RuleActionData> toCacheModel() {
		RuleActionDataCacheModel ruleActionDataCacheModel =
			new RuleActionDataCacheModel();

		ruleActionDataCacheModel.ruleActionDataId = getRuleActionDataId();

		ruleActionDataCacheModel.ruleActionId = getRuleActionId();

		ruleActionDataCacheModel.field = getField();

		String field = ruleActionDataCacheModel.field;

		if ((field != null) && (field.length() == 0)) {
			ruleActionDataCacheModel.field = null;
		}

		ruleActionDataCacheModel.value = getValue();

		String value = ruleActionDataCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			ruleActionDataCacheModel.value = null;
		}

		return ruleActionDataCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RuleActionData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RuleActionData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RuleActionData, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((RuleActionData)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RuleActionData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RuleActionData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RuleActionData, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((RuleActionData)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RuleActionData>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _ruleActionDataId;
	private long _ruleActionId;
	private long _originalRuleActionId;
	private boolean _setOriginalRuleActionId;
	private String _field;
	private String _value;
	private long _columnBitmask;
	private RuleActionData _escapedModel;

}