/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.rules.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.yithro.rules.model.RuleCondition;
import com.liferay.yithro.rules.model.RuleConditionModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RuleCondition service. Represents a row in the &quot;Yithro_RuleCondition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>RuleConditionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RuleConditionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RuleConditionImpl
 * @generated
 */
public class RuleConditionModelImpl
	extends BaseModelImpl<RuleCondition> implements RuleConditionModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rule condition model instance should use the <code>RuleCondition</code> interface instead.
	 */
	public static final String TABLE_NAME = "Yithro_RuleCondition";

	public static final Object[][] TABLE_COLUMNS = {
		{"ruleConditionId", Types.BIGINT}, {"ruleId", Types.BIGINT},
		{"type_", Types.VARCHAR}, {"field", Types.VARCHAR},
		{"operation", Types.VARCHAR}, {"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ruleConditionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ruleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("field", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("operation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Yithro_RuleCondition (ruleConditionId LONG not null primary key,ruleId LONG,type_ VARCHAR(75) null,field VARCHAR(75) null,operation VARCHAR(75) null,value VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Yithro_RuleCondition";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ruleCondition.ruleConditionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Yithro_RuleCondition.ruleConditionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long RULEID_COLUMN_BITMASK = 1L;

	public static final long TYPE_COLUMN_BITMASK = 2L;

	public static final long RULECONDITIONID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public RuleConditionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ruleConditionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRuleConditionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ruleConditionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RuleCondition.class;
	}

	@Override
	public String getModelClassName() {
		return RuleCondition.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RuleCondition, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RuleCondition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RuleCondition, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RuleCondition)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RuleCondition, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RuleCondition, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RuleCondition)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RuleCondition, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RuleCondition, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, RuleCondition>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			RuleCondition.class.getClassLoader(), RuleCondition.class,
			ModelWrapper.class);

		try {
			Constructor<RuleCondition> constructor =
				(Constructor<RuleCondition>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<RuleCondition, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RuleCondition, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RuleCondition, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<RuleCondition, Object>>();
		Map<String, BiConsumer<RuleCondition, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<RuleCondition, ?>>();

		attributeGetterFunctions.put(
			"ruleConditionId", RuleCondition::getRuleConditionId);
		attributeSetterBiConsumers.put(
			"ruleConditionId",
			(BiConsumer<RuleCondition, Long>)RuleCondition::setRuleConditionId);
		attributeGetterFunctions.put("ruleId", RuleCondition::getRuleId);
		attributeSetterBiConsumers.put(
			"ruleId",
			(BiConsumer<RuleCondition, Long>)RuleCondition::setRuleId);
		attributeGetterFunctions.put("type", RuleCondition::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<RuleCondition, String>)RuleCondition::setType);
		attributeGetterFunctions.put("field", RuleCondition::getField);
		attributeSetterBiConsumers.put(
			"field",
			(BiConsumer<RuleCondition, String>)RuleCondition::setField);
		attributeGetterFunctions.put("operation", RuleCondition::getOperation);
		attributeSetterBiConsumers.put(
			"operation",
			(BiConsumer<RuleCondition, String>)RuleCondition::setOperation);
		attributeGetterFunctions.put("value", RuleCondition::getValue);
		attributeSetterBiConsumers.put(
			"value",
			(BiConsumer<RuleCondition, String>)RuleCondition::setValue);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getRuleConditionId() {
		return _ruleConditionId;
	}

	@Override
	public void setRuleConditionId(long ruleConditionId) {
		_ruleConditionId = ruleConditionId;
	}

	@Override
	public long getRuleId() {
		return _ruleId;
	}

	@Override
	public void setRuleId(long ruleId) {
		_columnBitmask |= RULEID_COLUMN_BITMASK;

		if (!_setOriginalRuleId) {
			_setOriginalRuleId = true;

			_originalRuleId = _ruleId;
		}

		_ruleId = ruleId;
	}

	public long getOriginalRuleId() {
		return _originalRuleId;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (_originalType == null) {
			_originalType = _type;
		}

		_type = type;
	}

	public String getOriginalType() {
		return GetterUtil.getString(_originalType);
	}

	@Override
	public String getField() {
		if (_field == null) {
			return "";
		}
		else {
			return _field;
		}
	}

	@Override
	public void setField(String field) {
		_field = field;
	}

	@Override
	public String getOperation() {
		if (_operation == null) {
			return "";
		}
		else {
			return _operation;
		}
	}

	@Override
	public void setOperation(String operation) {
		_operation = operation;
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RuleCondition.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RuleCondition toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RuleCondition>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RuleConditionImpl ruleConditionImpl = new RuleConditionImpl();

		ruleConditionImpl.setRuleConditionId(getRuleConditionId());
		ruleConditionImpl.setRuleId(getRuleId());
		ruleConditionImpl.setType(getType());
		ruleConditionImpl.setField(getField());
		ruleConditionImpl.setOperation(getOperation());
		ruleConditionImpl.setValue(getValue());

		ruleConditionImpl.resetOriginalValues();

		return ruleConditionImpl;
	}

	@Override
	public int compareTo(RuleCondition ruleCondition) {
		long primaryKey = ruleCondition.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RuleCondition)) {
			return false;
		}

		RuleCondition ruleCondition = (RuleCondition)obj;

		long primaryKey = ruleCondition.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		RuleConditionModelImpl ruleConditionModelImpl = this;

		ruleConditionModelImpl._originalRuleId = ruleConditionModelImpl._ruleId;

		ruleConditionModelImpl._setOriginalRuleId = false;

		ruleConditionModelImpl._originalType = ruleConditionModelImpl._type;

		ruleConditionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<RuleCondition> toCacheModel() {
		RuleConditionCacheModel ruleConditionCacheModel =
			new RuleConditionCacheModel();

		ruleConditionCacheModel.ruleConditionId = getRuleConditionId();

		ruleConditionCacheModel.ruleId = getRuleId();

		ruleConditionCacheModel.type = getType();

		String type = ruleConditionCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			ruleConditionCacheModel.type = null;
		}

		ruleConditionCacheModel.field = getField();

		String field = ruleConditionCacheModel.field;

		if ((field != null) && (field.length() == 0)) {
			ruleConditionCacheModel.field = null;
		}

		ruleConditionCacheModel.operation = getOperation();

		String operation = ruleConditionCacheModel.operation;

		if ((operation != null) && (operation.length() == 0)) {
			ruleConditionCacheModel.operation = null;
		}

		ruleConditionCacheModel.value = getValue();

		String value = ruleConditionCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			ruleConditionCacheModel.value = null;
		}

		return ruleConditionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RuleCondition, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RuleCondition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RuleCondition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((RuleCondition)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RuleCondition, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RuleCondition, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RuleCondition, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((RuleCondition)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RuleCondition>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _ruleConditionId;
	private long _ruleId;
	private long _originalRuleId;
	private boolean _setOriginalRuleId;
	private String _type;
	private String _originalType;
	private String _field;
	private String _operation;
	private String _value;
	private long _columnBitmask;
	private RuleCondition _escapedModel;

}