/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.support.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SupportTeam service. Represents a row in the &quot;Yithro_SupportTeam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.yithro.support.model.impl.SupportTeamModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.yithro.support.model.impl.SupportTeamImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SupportTeam
 * @generated
 */
@ProviderType
public interface SupportTeamModel
	extends AuditedModel, BaseModel<SupportTeam>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a support team model instance should use the {@link SupportTeam} interface instead.
	 */

	/**
	 * Returns the primary key of this support team.
	 *
	 * @return the primary key of this support team
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this support team.
	 *
	 * @param primaryKey the primary key of this support team
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the support team ID of this support team.
	 *
	 * @return the support team ID of this support team
	 */
	public long getSupportTeamId();

	/**
	 * Sets the support team ID of this support team.
	 *
	 * @param supportTeamId the support team ID of this support team
	 */
	public void setSupportTeamId(long supportTeamId);

	/**
	 * Returns the company ID of this support team.
	 *
	 * @return the company ID of this support team
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this support team.
	 *
	 * @param companyId the company ID of this support team
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this support team.
	 *
	 * @return the user ID of this support team
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this support team.
	 *
	 * @param userId the user ID of this support team
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this support team.
	 *
	 * @return the user uuid of this support team
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this support team.
	 *
	 * @param userUuid the user uuid of this support team
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this support team.
	 *
	 * @return the user name of this support team
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this support team.
	 *
	 * @param userName the user name of this support team
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this support team.
	 *
	 * @return the create date of this support team
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this support team.
	 *
	 * @param createDate the create date of this support team
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this support team.
	 *
	 * @return the modified date of this support team
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this support team.
	 *
	 * @param modifiedDate the modified date of this support team
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the parent support team ID of this support team.
	 *
	 * @return the parent support team ID of this support team
	 */
	public long getParentSupportTeamId();

	/**
	 * Sets the parent support team ID of this support team.
	 *
	 * @param parentSupportTeamId the parent support team ID of this support team
	 */
	public void setParentSupportTeamId(long parentSupportTeamId);

	/**
	 * Returns the support labor ID of this support team.
	 *
	 * @return the support labor ID of this support team
	 */
	public long getSupportLaborId();

	/**
	 * Sets the support labor ID of this support team.
	 *
	 * @param supportLaborId the support labor ID of this support team
	 */
	public void setSupportLaborId(long supportLaborId);

	/**
	 * Returns the name of this support team.
	 *
	 * @return the name of this support team
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this support team.
	 *
	 * @param name the name of this support team
	 */
	public void setName(String name);

	/**
	 * Returns the description of this support team.
	 *
	 * @return the description of this support team
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this support team.
	 *
	 * @param description the description of this support team
	 */
	public void setDescription(String description);

	/**
	 * Returns the assigned work of this support team.
	 *
	 * @return the assigned work of this support team
	 */
	public double getAssignedWork();

	/**
	 * Sets the assigned work of this support team.
	 *
	 * @param assignedWork the assigned work of this support team
	 */
	public void setAssignedWork(double assignedWork);

	/**
	 * Returns the max work of this support team.
	 *
	 * @return the max work of this support team
	 */
	public double getMaxWork();

	/**
	 * Sets the max work of this support team.
	 *
	 * @param maxWork the max work of this support team
	 */
	public void setMaxWork(double maxWork);

}