/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.rules.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Rule service. Represents a row in the &quot;Yithro_Rule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.yithro.rules.model.impl.RuleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.yithro.rules.model.impl.RuleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Rule
 * @generated
 */
@ProviderType
public interface RuleModel extends BaseModel<Rule> {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rule model instance should use the {@link Rule} interface instead.
	 */

	/**
	 * Returns the primary key of this rule.
	 *
	 * @return the primary key of this rule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rule.
	 *
	 * @param primaryKey the primary key of this rule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rule ID of this rule.
	 *
	 * @return the rule ID of this rule
	 */
	public long getRuleId();

	/**
	 * Sets the rule ID of this rule.
	 *
	 * @param ruleId the rule ID of this rule
	 */
	public void setRuleId(long ruleId);

	/**
	 * Returns the name of this rule.
	 *
	 * @return the name of this rule
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this rule.
	 *
	 * @param name the name of this rule
	 */
	public void setName(String name);

	/**
	 * Returns the object name of this rule.
	 *
	 * @return the object name of this rule
	 */
	@AutoEscape
	public String getObjectName();

	/**
	 * Sets the object name of this rule.
	 *
	 * @param objectName the object name of this rule
	 */
	public void setObjectName(String objectName);

	/**
	 * Returns the object event of this rule.
	 *
	 * @return the object event of this rule
	 */
	@AutoEscape
	public String getObjectEvent();

	/**
	 * Sets the object event of this rule.
	 *
	 * @param objectEvent the object event of this rule
	 */
	public void setObjectEvent(String objectEvent);

}