/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.ticket.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

/**
 * The base model interface for the TicketInformation service. Represents a row in the &quot;Yithro_TicketInformation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.yithro.ticket.model.impl.TicketInformationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.yithro.ticket.model.impl.TicketInformationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketInformation
 * @generated
 */
@ProviderType
public interface TicketInformationModel extends BaseModel<TicketInformation> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket information model instance should use the {@link TicketInformation} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket information.
	 *
	 * @return the primary key of this ticket information
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket information.
	 *
	 * @param primaryKey the primary key of this ticket information
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ticket information ID of this ticket information.
	 *
	 * @return the ticket information ID of this ticket information
	 */
	public long getTicketInformationId();

	/**
	 * Sets the ticket information ID of this ticket information.
	 *
	 * @param ticketInformationId the ticket information ID of this ticket information
	 */
	public void setTicketInformationId(long ticketInformationId);

	/**
	 * Returns the create date of this ticket information.
	 *
	 * @return the create date of this ticket information
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ticket information.
	 *
	 * @param createDate the create date of this ticket information
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ticket information.
	 *
	 * @return the modified date of this ticket information
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ticket information.
	 *
	 * @param modifiedDate the modified date of this ticket information
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ticket entry ID of this ticket information.
	 *
	 * @return the ticket entry ID of this ticket information
	 */
	public long getTicketEntryId();

	/**
	 * Sets the ticket entry ID of this ticket information.
	 *
	 * @param ticketEntryId the ticket entry ID of this ticket information
	 */
	public void setTicketEntryId(long ticketEntryId);

	/**
	 * Returns the field ID of this ticket information.
	 *
	 * @return the field ID of this ticket information
	 */
	public long getFieldId();

	/**
	 * Sets the field ID of this ticket information.
	 *
	 * @param fieldId the field ID of this ticket information
	 */
	public void setFieldId(long fieldId);

	/**
	 * Returns the data of this ticket information.
	 *
	 * @return the data of this ticket information
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this ticket information.
	 *
	 * @param data the data of this ticket information
	 */
	public void setData(String data);

}