/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.ticket.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TicketStructure service. Represents a row in the &quot;Yithro_TicketStructure&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.yithro.ticket.model.impl.TicketStructureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.yithro.ticket.model.impl.TicketStructureImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketStructure
 * @generated
 */
@ProviderType
public interface TicketStructureModel
	extends AuditedModel, BaseModel<TicketStructure>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket structure model instance should use the {@link TicketStructure} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket structure.
	 *
	 * @return the primary key of this ticket structure
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket structure.
	 *
	 * @param primaryKey the primary key of this ticket structure
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ticket structure ID of this ticket structure.
	 *
	 * @return the ticket structure ID of this ticket structure
	 */
	public long getTicketStructureId();

	/**
	 * Sets the ticket structure ID of this ticket structure.
	 *
	 * @param ticketStructureId the ticket structure ID of this ticket structure
	 */
	public void setTicketStructureId(long ticketStructureId);

	/**
	 * Returns the company ID of this ticket structure.
	 *
	 * @return the company ID of this ticket structure
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ticket structure.
	 *
	 * @param companyId the company ID of this ticket structure
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ticket structure.
	 *
	 * @return the user ID of this ticket structure
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ticket structure.
	 *
	 * @param userId the user ID of this ticket structure
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ticket structure.
	 *
	 * @return the user uuid of this ticket structure
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ticket structure.
	 *
	 * @param userUuid the user uuid of this ticket structure
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ticket structure.
	 *
	 * @return the user name of this ticket structure
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ticket structure.
	 *
	 * @param userName the user name of this ticket structure
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ticket structure.
	 *
	 * @return the create date of this ticket structure
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ticket structure.
	 *
	 * @param createDate the create date of this ticket structure
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ticket structure.
	 *
	 * @return the modified date of this ticket structure
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ticket structure.
	 *
	 * @param modifiedDate the modified date of this ticket structure
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this ticket structure.
	 *
	 * @return the name of this ticket structure
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this ticket structure.
	 *
	 * @param name the name of this ticket structure
	 */
	public void setName(String name);

	/**
	 * Returns the description of this ticket structure.
	 *
	 * @return the description of this ticket structure
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this ticket structure.
	 *
	 * @param description the description of this ticket structure
	 */
	public void setDescription(String description);

	/**
	 * Returns the structure of this ticket structure.
	 *
	 * @return the structure of this ticket structure
	 */
	@AutoEscape
	public String getStructure();

	/**
	 * Sets the structure of this ticket structure.
	 *
	 * @param structure the structure of this ticket structure
	 */
	public void setStructure(String structure);

}