/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.ticket.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TicketFieldData service. Represents a row in the &quot;Yithro_TicketFieldData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.yithro.ticket.model.impl.TicketFieldDataModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.yithro.ticket.model.impl.TicketFieldDataImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketFieldData
 * @generated
 */
@ProviderType
public interface TicketFieldDataModel
	extends BaseModel<TicketFieldData>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket field data model instance should use the {@link TicketFieldData} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket field data.
	 *
	 * @return the primary key of this ticket field data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket field data.
	 *
	 * @param primaryKey the primary key of this ticket field data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ticket field data ID of this ticket field data.
	 *
	 * @return the ticket field data ID of this ticket field data
	 */
	public long getTicketFieldDataId();

	/**
	 * Sets the ticket field data ID of this ticket field data.
	 *
	 * @param ticketFieldDataId the ticket field data ID of this ticket field data
	 */
	public void setTicketFieldDataId(long ticketFieldDataId);

	/**
	 * Returns the company ID of this ticket field data.
	 *
	 * @return the company ID of this ticket field data
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ticket field data.
	 *
	 * @param companyId the company ID of this ticket field data
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this ticket field data.
	 *
	 * @return the create date of this ticket field data
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ticket field data.
	 *
	 * @param createDate the create date of this ticket field data
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ticket field data.
	 *
	 * @return the modified date of this ticket field data
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ticket field data.
	 *
	 * @param modifiedDate the modified date of this ticket field data
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ticket entry ID of this ticket field data.
	 *
	 * @return the ticket entry ID of this ticket field data
	 */
	public long getTicketEntryId();

	/**
	 * Sets the ticket entry ID of this ticket field data.
	 *
	 * @param ticketEntryId the ticket entry ID of this ticket field data
	 */
	public void setTicketEntryId(long ticketEntryId);

	/**
	 * Returns the ticket field ID of this ticket field data.
	 *
	 * @return the ticket field ID of this ticket field data
	 */
	public long getTicketFieldId();

	/**
	 * Sets the ticket field ID of this ticket field data.
	 *
	 * @param ticketFieldId the ticket field ID of this ticket field data
	 */
	public void setTicketFieldId(long ticketFieldId);

	/**
	 * Returns the data of this ticket field data.
	 *
	 * @return the data of this ticket field data
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this ticket field data.
	 *
	 * @param data the data of this ticket field data
	 */
	public void setData(String data);

}