/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.ticket.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TicketEntry service. Represents a row in the &quot;Yithro_TicketEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.yithro.ticket.model.impl.TicketEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.yithro.ticket.model.impl.TicketEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketEntry
 * @generated
 */
@ProviderType
public interface TicketEntryModel
	extends AuditedModel, BaseModel<TicketEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket entry model instance should use the {@link TicketEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket entry.
	 *
	 * @return the primary key of this ticket entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket entry.
	 *
	 * @param primaryKey the primary key of this ticket entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ticket entry ID of this ticket entry.
	 *
	 * @return the ticket entry ID of this ticket entry
	 */
	public long getTicketEntryId();

	/**
	 * Sets the ticket entry ID of this ticket entry.
	 *
	 * @param ticketEntryId the ticket entry ID of this ticket entry
	 */
	public void setTicketEntryId(long ticketEntryId);

	/**
	 * Returns the company ID of this ticket entry.
	 *
	 * @return the company ID of this ticket entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ticket entry.
	 *
	 * @param companyId the company ID of this ticket entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ticket entry.
	 *
	 * @return the user ID of this ticket entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ticket entry.
	 *
	 * @param userId the user ID of this ticket entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ticket entry.
	 *
	 * @return the user uuid of this ticket entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ticket entry.
	 *
	 * @param userUuid the user uuid of this ticket entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ticket entry.
	 *
	 * @return the user name of this ticket entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ticket entry.
	 *
	 * @param userName the user name of this ticket entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ticket entry.
	 *
	 * @return the create date of this ticket entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ticket entry.
	 *
	 * @param createDate the create date of this ticket entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ticket entry.
	 *
	 * @return the modified date of this ticket entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ticket entry.
	 *
	 * @param modifiedDate the modified date of this ticket entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ticket status ID of this ticket entry.
	 *
	 * @return the ticket status ID of this ticket entry
	 */
	public long getTicketStatusId();

	/**
	 * Sets the ticket status ID of this ticket entry.
	 *
	 * @param ticketStatusId the ticket status ID of this ticket entry
	 */
	public void setTicketStatusId(long ticketStatusId);

	/**
	 * Returns the language ID of this ticket entry.
	 *
	 * @return the language ID of this ticket entry
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this ticket entry.
	 *
	 * @param languageId the language ID of this ticket entry
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the ticket number of this ticket entry.
	 *
	 * @return the ticket number of this ticket entry
	 */
	public long getTicketNumber();

	/**
	 * Sets the ticket number of this ticket entry.
	 *
	 * @param ticketNumber the ticket number of this ticket entry
	 */
	public void setTicketNumber(long ticketNumber);

	/**
	 * Returns the subject of this ticket entry.
	 *
	 * @return the subject of this ticket entry
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this ticket entry.
	 *
	 * @param subject the subject of this ticket entry
	 */
	public void setSubject(String subject);

	/**
	 * Returns the description of this ticket entry.
	 *
	 * @return the description of this ticket entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this ticket entry.
	 *
	 * @param description the description of this ticket entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the weight of this ticket entry.
	 *
	 * @return the weight of this ticket entry
	 */
	public int getWeight();

	/**
	 * Sets the weight of this ticket entry.
	 *
	 * @param weight the weight of this ticket entry
	 */
	public void setWeight(int weight);

	/**
	 * Returns the hold date of this ticket entry.
	 *
	 * @return the hold date of this ticket entry
	 */
	public Date getHoldDate();

	/**
	 * Sets the hold date of this ticket entry.
	 *
	 * @param holdDate the hold date of this ticket entry
	 */
	public void setHoldDate(Date holdDate);

	/**
	 * Returns the closed date of this ticket entry.
	 *
	 * @return the closed date of this ticket entry
	 */
	public Date getClosedDate();

	/**
	 * Sets the closed date of this ticket entry.
	 *
	 * @param closedDate the closed date of this ticket entry
	 */
	public void setClosedDate(Date closedDate);

	/**
	 * Returns the due date of this ticket entry.
	 *
	 * @return the due date of this ticket entry
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this ticket entry.
	 *
	 * @param dueDate the due date of this ticket entry
	 */
	public void setDueDate(Date dueDate);

}