/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.ticket.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

/**
 * The base model interface for the TicketSolution service. Represents a row in the &quot;Yithro_TicketSolution&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.yithro.ticket.model.impl.TicketSolutionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.yithro.ticket.model.impl.TicketSolutionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketSolution
 * @generated
 */
@ProviderType
public interface TicketSolutionModel
	extends BaseModel<TicketSolution>, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket solution model instance should use the {@link TicketSolution} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket solution.
	 *
	 * @return the primary key of this ticket solution
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket solution.
	 *
	 * @param primaryKey the primary key of this ticket solution
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ticket solution ID of this ticket solution.
	 *
	 * @return the ticket solution ID of this ticket solution
	 */
	public long getTicketSolutionId();

	/**
	 * Sets the ticket solution ID of this ticket solution.
	 *
	 * @param ticketSolutionId the ticket solution ID of this ticket solution
	 */
	public void setTicketSolutionId(long ticketSolutionId);

	/**
	 * Returns the user ID of this ticket solution.
	 *
	 * @return the user ID of this ticket solution
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ticket solution.
	 *
	 * @param userId the user ID of this ticket solution
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ticket solution.
	 *
	 * @return the user uuid of this ticket solution
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ticket solution.
	 *
	 * @param userUuid the user uuid of this ticket solution
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ticket solution.
	 *
	 * @return the user name of this ticket solution
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this ticket solution.
	 *
	 * @param userName the user name of this ticket solution
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ticket solution.
	 *
	 * @return the create date of this ticket solution
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ticket solution.
	 *
	 * @param createDate the create date of this ticket solution
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the ticket entry ID of this ticket solution.
	 *
	 * @return the ticket entry ID of this ticket solution
	 */
	public long getTicketEntryId();

	/**
	 * Sets the ticket entry ID of this ticket solution.
	 *
	 * @param ticketEntryId the ticket entry ID of this ticket solution
	 */
	public void setTicketEntryId(long ticketEntryId);

	/**
	 * Returns the solution of this ticket solution.
	 *
	 * @return the solution of this ticket solution
	 */
	@AutoEscape
	public String getSolution();

	/**
	 * Sets the solution of this ticket solution.
	 *
	 * @param solution the solution of this ticket solution
	 */
	public void setSolution(String solution);

	/**
	 * Returns the type of this ticket solution.
	 *
	 * @return the type of this ticket solution
	 */
	public int getType();

	/**
	 * Sets the type of this ticket solution.
	 *
	 * @param type the type of this ticket solution
	 */
	public void setType(int type);

	/**
	 * Returns the status of this ticket solution.
	 *
	 * @return the status of this ticket solution
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this ticket solution.
	 *
	 * @param status the status of this ticket solution
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this ticket solution.
	 *
	 * @return the status by user ID of this ticket solution
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this ticket solution.
	 *
	 * @param statusByUserId the status by user ID of this ticket solution
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this ticket solution.
	 *
	 * @return the status by user uuid of this ticket solution
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this ticket solution.
	 *
	 * @param statusByUserUuid the status by user uuid of this ticket solution
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this ticket solution.
	 *
	 * @return the status by user name of this ticket solution
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this ticket solution.
	 *
	 * @param statusByUserName the status by user name of this ticket solution
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this ticket solution.
	 *
	 * @return the status date of this ticket solution
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this ticket solution.
	 *
	 * @param statusDate the status date of this ticket solution
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the status message of this ticket solution.
	 *
	 * @return the status message of this ticket solution
	 */
	@AutoEscape
	public String getStatusMessage();

	/**
	 * Sets the status message of this ticket solution.
	 *
	 * @param statusMessage the status message of this ticket solution
	 */
	public void setStatusMessage(String statusMessage);

	/**
	 * Returns the status reason of this ticket solution.
	 *
	 * @return the status reason of this ticket solution
	 */
	public int getStatusReason();

	/**
	 * Sets the status reason of this ticket solution.
	 *
	 * @param statusReason the status reason of this ticket solution
	 */
	public void setStatusReason(int statusReason);

	/**
	 * Returns <code>true</code> if this ticket solution is approved.
	 *
	 * @return <code>true</code> if this ticket solution is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this ticket solution is denied.
	 *
	 * @return <code>true</code> if this ticket solution is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this ticket solution is a draft.
	 *
	 * @return <code>true</code> if this ticket solution is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this ticket solution is expired.
	 *
	 * @return <code>true</code> if this ticket solution is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this ticket solution is inactive.
	 *
	 * @return <code>true</code> if this ticket solution is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this ticket solution is incomplete.
	 *
	 * @return <code>true</code> if this ticket solution is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this ticket solution is pending.
	 *
	 * @return <code>true</code> if this ticket solution is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this ticket solution is scheduled.
	 *
	 * @return <code>true</code> if this ticket solution is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}