/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.yithro.ticket.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TicketStatus service. Represents a row in the &quot;Yithro_TicketStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.yithro.ticket.model.impl.TicketStatusModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.yithro.ticket.model.impl.TicketStatusImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketStatus
 * @generated
 */
@ProviderType
public interface TicketStatusModel
	extends BaseModel<TicketStatus>, LocalizedModel, ShardedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket status model instance should use the {@link TicketStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket status.
	 *
	 * @return the primary key of this ticket status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket status.
	 *
	 * @param primaryKey the primary key of this ticket status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ticket status ID of this ticket status.
	 *
	 * @return the ticket status ID of this ticket status
	 */
	public long getTicketStatusId();

	/**
	 * Sets the ticket status ID of this ticket status.
	 *
	 * @param ticketStatusId the ticket status ID of this ticket status
	 */
	public void setTicketStatusId(long ticketStatusId);

	/**
	 * Returns the company ID of this ticket status.
	 *
	 * @return the company ID of this ticket status
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ticket status.
	 *
	 * @param companyId the company ID of this ticket status
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ticket status.
	 *
	 * @return the user ID of this ticket status
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ticket status.
	 *
	 * @param userId the user ID of this ticket status
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ticket status.
	 *
	 * @return the user uuid of this ticket status
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ticket status.
	 *
	 * @param userUuid the user uuid of this ticket status
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this ticket status.
	 *
	 * @return the create date of this ticket status
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ticket status.
	 *
	 * @param createDate the create date of this ticket status
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ticket status.
	 *
	 * @return the modified date of this ticket status
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ticket status.
	 *
	 * @param modifiedDate the modified date of this ticket status
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this ticket status.
	 *
	 * @return the name of this ticket status
	 */
	public String getName();

	/**
	 * Returns the localized name of this ticket status in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this ticket status
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this ticket status in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this ticket status. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this ticket status in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this ticket status
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this ticket status in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this ticket status
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this ticket status.
	 *
	 * @return the locales and localized names of this ticket status
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this ticket status.
	 *
	 * @param name the name of this ticket status
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this ticket status in the language.
	 *
	 * @param name the localized name of this ticket status
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this ticket status in the language, and sets the default locale.
	 *
	 * @param name the localized name of this ticket status
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this ticket status from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this ticket status
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this ticket status from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this ticket status
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Returns the description of this ticket status.
	 *
	 * @return the description of this ticket status
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this ticket status in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this ticket status
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this ticket status in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this ticket status. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this ticket status in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this ticket status
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this ticket status in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this ticket status
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this ticket status.
	 *
	 * @return the locales and localized descriptions of this ticket status
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this ticket status.
	 *
	 * @param description the description of this ticket status
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this ticket status in the language.
	 *
	 * @param description the localized description of this ticket status
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this ticket status in the language, and sets the default locale.
	 *
	 * @param description the localized description of this ticket status
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this ticket status from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this ticket status
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this ticket status from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this ticket status
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	/**
	 * Returns the order of this ticket status.
	 *
	 * @return the order of this ticket status
	 */
	public int getOrder();

	/**
	 * Sets the order of this ticket status.
	 *
	 * @param order the order of this ticket status
	 */
	public void setOrder(int order);

	/**
	 * Returns the terminal of this ticket status.
	 *
	 * @return the terminal of this ticket status
	 */
	public boolean getTerminal();

	/**
	 * Returns <code>true</code> if this ticket status is terminal.
	 *
	 * @return <code>true</code> if this ticket status is terminal; <code>false</code> otherwise
	 */
	public boolean isTerminal();

	/**
	 * Sets whether this ticket status is terminal.
	 *
	 * @param terminal the terminal of this ticket status
	 */
	public void setTerminal(boolean terminal);

	/**
	 * Returns the status of this ticket status.
	 *
	 * @return the status of this ticket status
	 */
	public int getStatus();

	/**
	 * Sets the status of this ticket status.
	 *
	 * @param status the status of this ticket status
	 */
	public void setStatus(int status);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}